import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import express from 'express'
import { Liquid } from 'liquidjs'
import { todoApp } from './app.ts'
import { databaseReachable, migrate } from './lib/db.ts'

const projectRoot = join(dirname(fileURLToPath(import.meta.url)), '..')

const isDev = process.env.NODE_ENV !== 'production'
const port = Number(process.env.PORT ?? 4000)

// Identifies this particular process. The browser holds on to it and compares
// it after an SSE reconnect; a different value means the server restarted and
// the open page is stale. See dev-reload.ts.
const bootId = `${process.pid}-${Date.now()}`
const bootTime = new Date().toISOString().replace('T', ' ').slice(0, 19)

const app = express()

const liquid = new Liquid({
  root: join(projectRoot, 'views'),
  extname: '.liquid',
  // Templates are re-read per request in dev, so editing a .liquid file shows
  // up immediately without restarting the server.
  cache: !isDev,
})

app.engine('liquid', liquid.express())
app.set('views', join(projectRoot, 'views'))
app.set('view engine', 'liquid')

app.use(express.static(join(projectRoot, 'public')))

// The exercise site, generated by Material for MkDocs and committed to
// exercises-site/. Deliberately not under public/: the hot reload watcher polls
// views/ and public/ every 300ms, and the generated site is 49 files and 2.6 MB
// (measured 2026-09-19) -- polling that on every attendee's machine, all
// session, buys nothing. See mkdocs.yml for how it is built.
app.use('/exercises', express.static(join(projectRoot, 'exercises-site')))

// Reports when the server is actually ready. It checks the
// database too, so "the server responds" cannot be true while the todo app is
// broken underneath.
app.get('/healthz', async (_req, res) => {
  if (await databaseReachable()) {
    res.type('text/plain').send('ok')
  } else {
    res.status(503).type('text/plain').send('database unreachable')
  }
})

app.get('/', (_req, res) => {
  res.render('index', {
    dev: isDev,
    nodeVersion: process.version,
    bootTime,
  })
})

app.use('/todo-app', todoApp)

if (isDev) {
  const { attachDevReload } = await import('./dev-reload.ts')
  await attachDevReload(app, { projectRoot, bootId })
}

// Applied before the first request, and again on every restart. See lib/db.ts.
await migrate()

app.listen(port, '0.0.0.0', () => {
  console.log(`\n  htmx-vassning-lab  ->  http://localhost:${port}\n`)
})
